[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.12"

[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig_wallet = "35QKMhSqHXEm4NamvyHiTH5DLCvkZKC6h3tqxmXZvAM1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"  # Use your default keypair

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"